name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "docker-mirror"
routes = [
  { pattern = "docker.zebplay.com", custom_domain = true },
  { pattern = "quay.zebplay.com", custom_domain = true },
  { pattern = "gcr.zebplay.com", custom_domain = true },
  { pattern = "k8s-gcr.zebplay.com", custom_domain = true },
  { pattern = "k8s.zebplay.com", custom_domain = true },
  { pattern = "ghcr.zebplay.com", custom_domain = true },
  { pattern = "cloudsmith.zebplay.com", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

# [env.staging]
# name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.zebplay.com", custom_domain = true }

# [env.staging.vars]
# MODE = "staging"
# TARGET_UPSTREAM = ""
